To test the Bipolar Continuum Hypothesis of Neff, which posits a reciprocal relationship between the compassionate (CS) and uncompassionate (UCS) components of self-compassion, a hierarchical Bayesian model was implemented using Stan. Our data comprised measurements from 169 participants, each assessed up to five times a day across up to sixteen days, yielding a total of N observations. Additionally, each measurement occasion included assessments of momentary negative affect, decentering, and valence evaluation of the context.

The model accounts for the hierarchical nature of the data, with observations nested within multiple levels: measurements, days, and participants. This structure allows for the analysis of within-person variability over time and across different conditions. The model estimates fixed effects for the intercept of UCS (alpha_ucs), the overall effect of CS on UCS (beta_cs), and coefficients for the three covariates: negative affect, decentering, and context evaluation (beta_covariates). To capture individual differences and temporal fluctuations, the model includes random intercepts for participants (z_participant), days (z_day), and measurements (z_measurement). Additionally, it estimates random slopes for the effect of CS at the participant level (z_participant_slope_cs).


```{r}
fit <- readRDS(
  here::here("data/prep/ema/brms_fits/fit_mod_9_rnd_slopes_bip_cont_hyp.RDS")
)
```

